[tools]
erlang = { version = "28.3.1" }
elixir = { version = "1.19.5-otp-28" }
fzf = "latest"
rg = "latest"
fd = "latest"
"github:cli/cli" = "latest"
"aqua:tldr-pages/tlrc" = "latest"
colima = "latest"
docker-cli = "latest"
yq = "latest"
pnpm = "latest"
difftastic = "latest"
k9s = "latest"
helm = "latest"
"github:elixir-lang/expert" = "v0.1.4"
kubectx = "latest"
gcloud = "latest"
neovim = "0.11.7"
zig = "0.16.0"

# colordiff
# shellcheck
# colima
# oath-toolkit
# gpg
